<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.1.0.0</Version>
    <Description>Move the flying text and set the HUD to the pixel from the HUD layout editor.</Description>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FlyingTextModifier.Tests" />
  </ItemGroup>
</Project>
